# Generated by Django 5.1.7 on 2025-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
